by_composition: false
learning_rate: 0.005
losses:
  bidir-cons-dice: false
  bidir-cons-reg: false
  compo-dice-down: true
  compo-dice-up: true
  compo-reg-down: true
  compo-reg-up: true
n_channels: 1
n_classes: 2
selected_slices:
- 107
- 153
- 199
shape:
- 256
- 256
way: both
weight_decay: 1.0e-08
